# Generated by Django 4.1.7 on 2023-10-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mydata', 
            new_name='Project',
        ),
    ]
